# Fase 1 - Data Analytics - Analise de dados Storytelling

## Aula 3 - Analisando dados com python I

In [10]:
# Bibliotecas para manipulação e análise de dados
import pandas as pd
import numpy as np

# Bibliotecas para visualização de dados
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [11]:
# Lê o arquivo Excel e armazena no DataFrame df_dengue
df_dengue = pd.read_excel('/content/sample_data/Base de Dados Dengue.xlsx')

# Exibe as primeiras 5 linhas do DataFrame (índice começa em 0)
df_dengue.head()

               municipio  uf data_infeccoes  qtd_infeccoes
0  ALTA FLORESTA D'OESTE  RO     2013-01-01             34
1  ALTA FLORESTA D'OESTE  RO     2013-02-01             44
2  ALTA FLORESTA D'OESTE  RO     2013-03-01             15
3  ALTA FLORESTA D'OESTE  RO     2013-04-01              4
4  ALTA FLORESTA D'OESTE  RO     2013-05-01              3

In [12]:
# Exibe as últimas 5 linhas do DataFrame
df_dengue.tail()

       municipio  uf data_infeccoes  qtd_infeccoes
728767  BRASILIA  DF     2023-08-01            939
728768  BRASILIA  DF     2023-09-01            843
728769  BRASILIA  DF     2023-10-01            686
728770  BRASILIA  DF     2023-11-01           1300
728771  BRASILIA  DF     2023-12-01           5603

## Aula 3 - Analisando dados com python II

In [17]:
# Retorna a quantidade de linhas e colunas do DataFrame: df_dengue.shape
print(f'Tamanho do DataSet: {df_dengue.shape}')

Tamanho do DataSet: (728772, 4)

In [19]:
# Retorna o tipo de dado de cada coluna do DataFrame (object geralmente representa texto)
df_dengue.dtypes

municipio                 object
uf                        object
data_infeccoes    datetime64[ns]
qtd_infeccoes              int64
dtype: object

In [21]:
# Verifica valores nulos no DataFrame, indicando onde há dados ausentes (True para nulo, False para preenchido)
df_dengue.isnull()

        municipio     uf  data_infeccoes  qtd_infeccoes
0           False  False           False          False
1           False  False           False          False
2           False  False           False          False
3           False  False           False          False
4           False  False           False          False
...           ...    ...             ...            ...
728767      False  False           False          False
728768      False  False           False          False
728769      False  False           False          False
728770      False  False           False          False
728771      False  False           False          False

[728772 rows x 4 columns]

In [22]:
# Retorna a quantidade de valores nulos por coluna, auxiliando na identificação de dados ausentes
df_dengue.isnull().sum()

municipio         0
uf                0
data_infeccoes    0
qtd_infeccoes     0
dtype: int64

In [25]:
# Retorna o total geral de valores nulos no DataFrame, somando todas as colunas
# df_dengue.isnull().sum().sum()

print(f'Quantidade de dados nulos: {df_dengue.isnull().sum().sum()}')

Quantidade de dados nulos: 0

In [28]:
# Exibe informações gerais do DataFrame, como quantidade de linhas, colunas, tipos de dados e valores não nulos
df_dengue.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 728772 entries, 0 to 728771
Data columns (total 4 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   municipio       728772 non-null  object
 1   uf              728772 non-null  object
 2   data_infeccoes  728772 non-null  datetime64[ns]
 3   qtd_infeccoes   728772 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 22.2+ MB

In [30]:
# Retorna a quantidade de valores únicos em cada coluna do DataFrame
df_dengue.nunique()

municipio         5243
uf                  27
data_infeccoes     132
qtd_infeccoes     1157
dtype: int64

Calcular a quantidade de pessoas que pegaram dengue por ano

In [37]:
# Cria uma nova coluna com o ano extraído da coluna de data de infecções
df_dengue ['ano'] = df_dengue['data_infeccoes'].dt.year
df_dengue.head()

               municipio  uf data_infeccoes  qtd_infeccoes   ano
0  ALTA FLORESTA D'OESTE  RO     2013-01-01             34  2013
1  ALTA FLORESTA D'OESTE  RO     2013-02-01             44  2013
2  ALTA FLORESTA D'OESTE  RO     2013-03-01             15  2013
3  ALTA FLORESTA D'OESTE  RO     2013-04-01              4  2013
4  ALTA FLORESTA D'OESTE  RO     2013-05-01              3  2013

In [43]:
# Agrupa os dados por ano, município e UF, somando a quantidade de infecções e reorganizando o índice
infeccoes_minicipio = df_dengue.groupby(['ano', 'municipio', 'uf'])['qtd_infeccoes'].sum().reset_index()
infeccoes_minicipio.head()

    ano            municipio  uf  qtd_infeccoes
0  2013      ABADIA DE GOIAS  GO             52
1  2013  ABADIA DOS DOURADOS  MG              0
2  2013            ABADIANIA  GO             37
3  2013               ABAETE  MG            486
4  2013           ABAETETUBA  PA             15

In [44]:
infeccoes_minicipio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60731 entries, 0 to 60730
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ano            60731 non-null  int32
 1   municipio      60731 non-null  object
 2   uf             60731 non-null  object
 3   qtd_infeccoes  60731 non-null  int64
dtypes: int32(1), int64(1), object(2)
memory usage: 1.6+ MB

In [52]:
# Agrupa os dados por ano e UF, somando a quantidade de infecções por estado
infeccoes_estado = df_dengue.groupby(['ano', 'uf'])['qtd_infeccoes'].sum().reset_index()
infeccoes_estado.head()

    ano  uf  qtd_infeccoes
0  2013  AC           1663
1  2013  AL            704
2  2013  AM           4327
3  2013  AP            546
4  2013  BA          13417